Refined go:embed handling for Go projects
jfrog/ide-plugins-common pull request #152
Opened 2023-11-30 14:14 UTC by noyshabtay

- [x] All [tests](https://github.com/jfrog/ide-plugins-common/actions/workflows/test.yml) passed. If this feature is not already covered by the tests, I added new tests.
-----
* Fixed warning created by go:embed files.
* go:embed test with a project resource were added.
* User get notification in case go list command had errors.
* Removed code warnings in files.

2023-11-30 14:49 UTC, yahavi requested changes

2023-11-30 14:49 UTC, yahavi commented on src/main/java/com/jfrog/ide/common/go/GoScanWorkspaceCreator.java
> +            return FileVisitResult.SKIP_SUBTREE;
More efficient to have these lines in preVisitDirectory

2023-11-30 14:49 UTC, yahavi commented on src/main/java/com/jfrog/ide/common/go/GoScanWorkspaceCreator.java
> +        if (StringUtils.containsAny(fileName, ".git", ".idea", ".vscode")) {
Let's put the list of excluded directories in private static final class variables.

2023-11-30 14:49 UTC, yahavi commented on src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
> +            logger.error("Errors occurred during building the Go dependency tree. The dependency tree may be incomplete:" +
I think it is more warning than error because the user will still see a dependency tree

2023-11-30 14:49 UTC, yahavi commented on src/test/java/com/jfrog/ide/common/go/GoTreeBuilderTest.java
> +        treeBuilder.buildTree();
Let's also check the returned dependency tree

2023-11-30 14:49 UTC, yahavi commented on src/test/resources/go/embedProject/main.go
> +
```suggestion
```

2023-12-03 09:47 UTC, asafgabai requested changes

2023-12-03 09:47 UTC, asafgabai commented on src/test/resources/go/embedProject/go.mod
I'm not sure what it is, but I think there's a problem with this file. I googled this red mark and it indicates that there's a syntax error. I can't find a syntax error, but maybe fixing the indentations will make it disappear.

2023-12-03 09:47 UTC, asafgabai commented on src/test/resources/go/embedProject/version.txt
I suggest changing this file to be not empty and add a test that checks the files that are copied to the temporary directory, and validates that this file was not copied with its content.

2023-12-03 13:02 UTC, merged