when readCommonCache occur error, log exception message
jfrog/ide-plugins-common pull request #83
Opened 2022-06-17 12:34 UTC by uyong

when i use this artifact and build-info-extractor-2.35.0, ScanCacheMap.readCommonCache() will occur error, but i don't know what exception. Later, although I learned that it was a build-info-extractor version problem, I thought that this exception information should not be lost, but should be recorded.

2022-06-17 12:35 UTC, uyong commented
I have read the CLA Document and I hereby sign the CLA

2022-06-17 12:36 UTC, uyong commented
I have read the CLA Document and I hereby sign the CLA

2022-06-27 12:15 UTC, uyong commented
@eyalbe4 hi, can you speed up processing? thank

2022-07-15 15:25 UTC, yahavi requested changes
Thanks for this contribution, @uyong!
Please consider my inline comment.

2022-07-15 15:25 UTC, yahavi commented on src/main/java/com/jfrog/ide/common/persistency/ScanCacheMap.java
> +            Utils.logError(logger, "Failed reading cache file, zapping the old cache and starting a new one.", e,false);
```suggestion
            Utils.logError(logger, "Failed reading cache file, zapping the old cache and starting a new one.", e, false);
```

2022-10-19 15:33 UTC, merged